#!/usr/bin/env bash

function help() {
    cat << EOF

aoc - a little helper tool for the "Advent of Code"

Usage:  aoc h|help         this help text
            l|ls|list [n]  list today's or given day's file(s)
            d|descr [n]    edit today's or given day's description file
            e|edit [n]     edit today's or given day's script(s)
            r|run [n]      run  today's or given day's script(s)
            t|test [n]     test today's or given day's script(s) with test-input
            p|pytest [n]   test today's or given day's script(s) via pytest
            i|ide|tmux     create a simple IDE with the help of tmux

EOF
}


function ideinfo() {
    cat <<EOF

I'm using 'aoc edit' in this window/pane here
and 'aoc run' in the window/pane bottom-right.

If tmux is configured for mouse wheel scrolling you can
easily scroll the puzzle description below.

Unfortunately copy/pasting within tmux is a bit strange.
More infos later. Tip: Use fullscreen (C-B z) for pasting.

EOF
}


function prepare_scripts() {
    SCRIPT_TEMPLATE=$(cat <<EOF
#!/usr/bin/env python3
"""
Advent of Code. Puzzle ${day}
"""

import sys


def main():

    #lines = (line.rstrip() for line in sys.stdin)
    print("todo...")


if __name__ == "__main__":
    main()

EOF
)
    for scriptidx in a b; do
        script=day${day}${scriptidx}.py
        if [ ! -f $script ] ; then
            echo "$SCRIPT_TEMPLATE" > $script
        fi
    done

    scripts=$(ls -1 day${day}[ab].py)
    chmod u+x $scripts
}


function run_scripts() {
    echo "---"
    for script in $scripts ; do
        ./$script < $input
        echo "---"
    done
}

#===========================================================================

if [ "$#" -eq 0 ] ; then
    help
    exit 1
fi

if [ -z "$2" ] ; then
    day=$(date +'%d')
else
    # leading zeros are eliminated from input (due to octal system trap...)
    # but there is no additional error checking yet (1..24, no-number etc.)
    printf -v day "%02i" ${2##*0}
fi

input=day${day}-input

if [ ! -f "$input" ] ; then
    echo "No input file '$input' found! Probably day ${day} has not been worked at."
    echo -e "Please paste the input data into the editor after pressing ENTER now"
    read inp
    vim $input
    exit 0
    if [ ! -f "$input" ] ; then
        echo "Still no input file found..."
        exit 2
    fi
fi

prepare_scripts

case "$1" in
    i|ide|tmux) if [[ ! $(type -P tmux) ]] ; then
                    echo "tmux doesn't seem to be installed!"
                    echo "Can't create the IDE..."
                    exit 3
                fi
                # put current directory into PATH to be able to execute aoc without ./
                export PATH=.:$PATH

                tmux has-session -t AOC 2>/dev/null
                if [ $? -ne 0 ] ; then
                    tmux new-session -d -s AOC
                    # Split window into 4 identical panes.
                    # Start with a horizontal split to be able
                    # to more comfortable resize panes later.
                    tmux split-window -t 0 -h -d
                    tmux split-window -t 0 -v -d
                    tmux split-window -t 2 -v -d

                    # There is an optional leading space in the sent commands
                    # to make them NOT stored in Bash history.
                    # If configured so there...
                    tmux send-keys -t 0 " aoc H" ENTER
                    if [ -f day${day}.txt ] ; then
                        tmux send-keys -t 1 " cat day${day}.txt" ENTER
                    else
                        tmux send-keys -t 1 " vi day${day}.txt" ENTER
                    fi
                    tmux send-keys -t 2 " python3" ENTER
                    tmux send-keys -t 3 " aoc ls ${day}" ENTER
                fi
                tmux attach -t AOC
                ;;
    l|ls|list)  echo "Files for day ${day}:"
                ls -l day${day}*
                ;;
    r|run)    run_scripts
              ;;
    t|test)   input=day${day}-testinput
              run_scripts
              ;;
    e|edit)   vim -p $scripts
              ;;
    d|descr)  vim day${day}.txt
              ;;
    p|pytest) pytest $scripts
              ;;
    h|help)   help
              exit 1
              ;;
          H)  help
              ideinfo
              ;;
esac

